# Generated by Django 4.2.5 on 2023-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydj1', '0002_autorisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=100, verbose_name='Login')),
                ('pas', models.CharField(max_length=150, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='autorisations',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
    ]
