# Generated by Django 4.2.5 on 2023-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydj1', '0003_registration_alter_autorisations_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorisations',
            name='email',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default=0, max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
