# Generated by Django 4.2.5 on 2023-10-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydj1', '0004_remove_autorisations_email_registration_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='UserModel',
        ),
        migrations.DeleteModel(
            name='Autorisations',
        ),
    ]
